version: '2'
 
services:

  mysql:
    image: mysql:latest 
    container_name: mysql
    networks:
      - mainproxy
    ports:
      - 3320:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kieserverdb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password

 
  kie-server: 
    image: gennyproject/kie-server:latest  
    container_name: kie-server
    ports:
      - 8230:8230
    links:
      - mysql:kieserverdb
    networks:
      - mainproxy


volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local 
networks:
  mainproxy:
    driver: bridge 


